---
title: "program01"
author: "pugal"
date: "2026-07-04"
output: html_document
---

```{r}
library(tidyverse)
library(ISLR)
library(ISLR2)
```
```{r}
data("Auto")
view(Auto)
```


```{r}
str(Auto)
```

```{r}
sapply(Auto[,1:7], range)
```

```{r}
sapply(Auto[,1:7], mean)
sapply(Auto[,1:7], sd)
```

```{r}
Auto.reduced = Auto[-c(10:84),]
sapply(Auto.reduced[,1:7], range)
sapply(Auto.reduced[,1:7], mean)
sapply(Auto.reduced[,1:7], sd)
```

```{r}
pairs(Auto[,1:7])
```
```{r}
cor(Auto[,1:7])
```



```{r}
data("college")
view(College)
```


```{r}
dim(College)
```


```{r}
summary(College)
```
```{r}
pairs(College[,1:5])
```




```{r}
Elite=rep("NO",nrow(College))
Elite[College$Top10perc>50]="YES"
College.df=data.frame(College,Elite)
summary(College.df)
```


```{r}
par(mfrow=c(2,2))
hist(College$Apps,Xlim=c(0,25000),xlab ="Applications",main = "Apps using default bin size")
hist(College$Apps,Xlim=c(0,25000),breaks=25,xlab ="Applications",main = "Apps using default bin size")
hist(College$Top10perc,breaks=25,xlab="Pct.new students from top 10%of H.S. class",main="Top10perc")
hist(College$Outstate,xlab="Out-of-state tuition",ylab="Amount",main="Outstate")
```


