---
title: "Model Exam"
output: html_document
date: "2026-10-08"
---
```{r}
library(ISLR)
data(Auto)
```


```{r}
View(Auto)
dim(Auto)
```


```{r}
str(Auto)
```


```{r}
summary(Auto)
```


```{r}
mpg01<-rep(0,nrow(Auto))
mpg01[Auto[,'mpg']>median(Auto[,'mpg'])]<-1
mpg01=as.factor(mpg01)
Auto01=data.frame(Auto,mpg01)
table(mpg01)
```


```{r}
par(mfrow=c(2,2))
```


```{r}
boxplot(displacement~mpg01,Auto,main="displ~mpg01")
boxplot(acceleration~mpg01,Auto,main="Accel~mpg01")
boxplot(weight~mpg01,Auto,main="weight~mpg01")
boxplot(horsepower~mpg01,Auto,main="horsep~mpg01")
```


```{r}
training_data=data(1:196,)
testing_data=data(196:392,)
```


```{r}
logit_fit=glm(mpg01~horsepower+displacement,family="binomial",training_data)
summary(logit_fit)
```


```{r}
library(MASS)
data(Boston)

```



```{r}
crim_med=rep(0,nrow(Boston))
crim_med[Boston$crim>median(Boston$crim)]<-1
Boston=data.frame(Boston,crim_med)
set.seed(312)
training_data=sample(nrow(Boston),size=0.75*nrow(Boston))
length(training_data)
```


```{r}
glm_fit=glm(crim_med~.,data=Boston,subset=training_data,family="binomial")
summary(glm_fit)
```


```{r}
```

