---
title: "PROGRAM9_1U24DS031"
author: "SDPRASANTH"
date: "2026-09-23"
---
```{r}
library(ISLR)
```
```{r}
data(Smarket)
attach(Smarket)
names(Smarket)
dim(Smarket )
summary(Smarket)
```

```{r}
train=(Year <2005)
Smarket.2005= Smarket [!train ,]
dim(Smarket.2005)
```
```{r}
Direction.2005= Direction [!train]
```
```{r}
glm.fit=glm(Direction∼Lag1+Lag2+Lag3+Lag4+Lag5+Volume ,
data=Smarket ,family=binomial ,subset=train)
glm.probs=predict (glm.fit,Smarket.2005, type="response")
```
```{r}
glm.pred=rep("Down",252)
glm.pred[glm.probs >.5]=" Up"
table(glm.pred ,Direction.2005)
```
```{r}
mean(glm.pred==Direction.2005)
```
```{r}
mean(glm.pred!=Direction.2005)
```
```{r}
glm.fit=glm(Direction∼Lag1+Lag2 ,data=Smarket ,family=binomial ,
subset=train)
glm.probs=predict (glm.fit ,Smarket.2005, type="response")
glm.pred=rep("Down",252)
glm.pred[glm.probs >.5]=" Up"
table(glm.pred ,Direction.2005)
```
```{r}
mean(glm.pred==Direction.2005)
```
```{r}
106/(106+76)
```
```{r}
predict (glm.fit ,newdata =data.frame(Lag1=c(1.2 ,1.5),
Lag2=c(1.1,-0.8) ),type="response")
```






