---
title: "prograsm_5"
author: "SHAFIYA"
date: "2026-08-28"
output: html_document
---

```{r}
library(tidyverse)
library(ISLR)
library(MASS)
```


```{r}
data(Auto)
```

```{r}
Auto=data.frame(Auto)
```

```{r}
?Auto
```

```{r}
view(Auto)
```

```{r}
attach(Auto)
```

```{r}
summary(Auto)
```

```{r}
head(Auto)
```

```{r}
tail(Auto)
```

```{r}
dim(Auto)
```

```{r}
pairs(Auto)
```

```{r}
mpg01<-rep(0,nrow(Auto))
mpg01[Auto[,'mpg']>median(Auto[,'mpg'])]<-1
mpg01=as.factor(mpg01)
auto01=data.frame(Auto,mpg01)
table(mpg01)
```

```{r}
par(mfrow=c(2,2))
boxplot(acceleration~mpg01,auto01,main="accel~mpg01")
boxplot(weight~mpg01,auto01,main="weight~mpg01")  
boxplot(horsepower~mpg01,auto01,main="horsep~mpg01")
boxplot(displacement~mpg01,auto01,main="disp~mpg01")        
        
```

```{r}
training_data=auto01[1:196,]
testing_data=auto01[196:392,]
```

```{r}
logit_fit=glm(mpg01~horsepower+displacement,family=binomial,training_data)
summary(logit_fit)
```
```{r}
logit_pred=predict(logit_fit,testing_data[,c('horsepower','weight','displacement')])
logit_class=ifelse(logit_pred>0.5,1,0)
table(logit_class,testing_data[,'mpg01'])
```
```{r}
(65+95)/(65+35+2+95)
```

