---
title: "Program 2_1u24ds037"
author: "vijayakumar"
date: "2026-07-10"
output: html_document
---
```{r}
library(tidyverse)
library(ISLR)
library(ISLR2)
```

```{r}
data("Auto")
attach(Auto)
```

```{r}
head(Auto)
tail(Auto)
summary(Auto)
```
```{r}
view(Auto)
dim(Auto)
str(Auto)
```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(range(Auto[,i]))  
}
```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(median(Auto[,i]))  
}
```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(mean(Auto[,i]))  
}
```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(sd(Auto[,i]))  
}

```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(summary(Auto[,i]))  
}

```

```{r}
remove=Auto[-c(10:85),]

```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(range(remove[,i]))  
}

```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(median(remove[,i]))  
}
```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(mean(remove[,i]))  
}
```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(sd(remove[,i]))  
}
```
```{r}
for (i in c(1,3,4,5,6,7)){
  print(summary(remove[,i]))  
}

```
```{r}
plot(Auto$horsepower,Auto$mpg
  )
```
```{r}
pairs(Auto)
```
```{r}
plot(Auto$origin,Auto$mpg)
```

