---
title: "EXERCISE"
output: html_document
date: "2026-07-04"
---

```{r}
library(tidyverse)
library(ISLR)
library(ISLR2)
```


```{r}
sapply(Auto[,1:7], range)
```
```{r}
sapply(Auto[,1:7], mean)
```
```{r}
data(Auto)
```


```{r}
summary(Auto)
```


```{r}
str(Auto)
```


```{r}
sapply(Auto[,1:7], sd)

```
```{r}
Auto.reduced = Auto[-c(10:84),]
```


```{r}
data(College)
```


```{r}
view(College)
```


```{r}
summary(College)
```


```{r}
pairs(College[,1:5])
```
```{r}
Elite=rep("No",nrow(College))
Elite[College$Top10perc>50]="yes"
College.df=data.frame(College,Elite)

```

```{r}
summary(College.df)

```
```{r}
view(College)
```


```{r}
str(College)
```
```{r}
boxplot(Outstate~Elite,data=College.df)
```


```{r}
hist(College$Apps,xlim=c(0,25000),xlab="Applications",main="Apps using default bin sizes")
```
```{r}
hist(College$Apps,xlim=c(0,25000),breaks=25,xlab="Applications",main="Apps using smaller bin sizes")
```

```{r}
```


```{r}
hist(College$Top10perc,breaks=25,xlab="Pct.new students from top 10% of H.S.class",main="Top10perc")
```


```{r}
Summary(College)


```

```


```{r}
`

```

```


``


```

