---
title: "program 5"
author: "Vijayakumar"
date: "2026-08-28"
output: html_document
---

```{r}
library(MASS)
library(tidyverse)
library(ISLR)
```
```{r}
data(Auto)
Auto=data.frame(Auto)
```
```{r}
?Auto
```

```{r}
View(Auto)
```

```{r}
dim(Auto)
```
```{r}
attach(Auto)

```

```{r}
head(Auto)
tail(Auto)
```


```{r}
mpg01<-rep(0,nrow(Auto))
mpg01[Auto[,"mpg"]>median(Auto[,"mpg"])]<-1
mpg01<-as.factor(mpg01)
data<-data.frame(Auto,mpg01)
table(mpg01)
```
```{r}
par(mfrow=c(2,2))
boxplot(acceleration~mpg01,data,mai="Accel~mpg01" )
boxplot(weight~mpg01,data,main="Weight~mpg01")
boxplot(horsepower~mpg01,data,main="horse~mpg01")
boxplot(displacement~mpg01,data,main="disp~mpg01")
```
```{r}
data.train=data[1:196,]
data.test=data[196:392,]
```
```{r}
logit.fit=glm(mpg01~horsepower+displacement,family = binomial,data.train)
summary(logit.fit)
```

```{r}
logit.pred=predict(logit.fit,data.test[,c('horsepower','weight','displacement')])
logit.class=ifelse(logit.pred>0.5,1,0)
table(logit.class,data.test[,'mpg01'])
```

```{r}
mean(logit.class!=data.test[,"mpg01"])
```
```{r}
logit.class=ifelse(logit.pred>0.25,1,0)
table(logit.class,data.test[,'mpg01'])
```
























