---
title: "program3"
author: "rithika"
date: "2026-08-11"
output: html_document
---

```{r}
library(tidyverse)
```
```{r}
library(MASS)
```
```{r}
data(Boston)
```
```{r}
view(Boston)
```
```{r}
tail(Boston)
```


```{r}
head(Boston)
```
```{r}
dim(Boston)
```


```{r}
summary(Boston)
```
```{r}
?Boston
```

```{r}
model1=lm(medv~crim,data=Boston)
```


```{r}
summary(model1)
```
```{r}
model2=lm(medv~zn,data=Boston)
summary(model2)
```
```{r}
model3=lm(medv~indus,data=Boston)
summary(model3)

```
```{r}
model4=lm(medv~chas,data=Boston)
summary(model4)
```
```{r}
model5=lm(medv~nox,data=Boston)
summary(model5)
```
```{r}
model6=lm(medv~rm,data=Boston)
summary(model6)
```
```{r}
model7=lm(medv~age,data=Boston)
summary(model7)
```
```{r}
model8=lm(medv~dis,data=Boston)
summary(model8)
```
```{r}
model9=lm(medv~rad,data=Boston)
summary(model9)
```
```{r}
model10=lm(medv~tax,data=Boston)
summary(model10)
```
```{r}
model11=lm(medv~ptratio,data=Boston)
summary(model11)
```
```{r}
```


```{r}
model12=lm(medv~black,data=Boston)
summary(model12)
```
```{r}
model13=lm(medv~lstat,data=Boston)
summary(model13)
```
```{r}
model_mlm=lm(medv~.,data=Boston)
summary(model_mlm)
```
```{r}
model_mlm=lm(medv~crim+tax+black+rad,data=Boston)
summary(model_mlm)
```


