---
title: "program-10"
author: "program"
date: "2026-09-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
```

```{r}
library(MASS)
```

```{r}
data("Smarket")
```

```{r}
train=(Year<2005)
```

```{r}
lda.fit=lda(Direction∼Lag1+Lag2,data=Smarket,subset=train)
lda.fit
```
```{r}
lda.pred=predict(lda.fit,Smarket.2005)
names(lda.pred)
```
```{r}
lda.class=lda.pred$class
table(lda.class ,Direction.2005)
Direction.2005
```
```{r}
mean(lda.class==Direction.2005)
```
```{r}
sum(lda.pred$posterior[,1]>=.5)
```
```{r}
sum(lda.pred$posterior[,1]<.5)
```
```{r}
lda.pred$posterior[1:20,1]
```
```{r}
lda.class[1:20]
```
```{r}
sum(lda.pred$posterior[,1]>.9)
```
```{r}
qda.fit=qda(Direction∼Lag1+Lag2,data=Smarket,subset=train)
qda.fit
```
```{r}
qda.class=predict (qda.fit,Smarket.2005)$class
table(qda.class ,Direction.2005)
Direction.2005
```
```{r}
mean(qda.class==Direction.2005)
```
```{r}

```















