---
title: "Untitled"
author: "1U24DS008"
date: "2026-08-11"
output: html_document
---

```{r}
library(tidyverse)
library(MASS)
```
```{r}
data(Boston)
```
```{r}
attach(Boston)
```
```{r}
view(Boston)
```
```{r}
?Boston
```
```{r}
m1=lm(medv~crim,data=Boston)
summary(m1)
```
```{r}
m2=lm(medv~zn,data=Boston)
summary(m2)
```
```{r}
m3=lm(medv~indus,data=Boston)
summary(m3)
```
```{r}
m5=lm(medv~nox,data=Boston)
summary(m5)
```
```{r}
m6=lm(medv~nox,data=Boston)
summary(m6)
```
```{r}
m7=lm(medv~rm,data=Boston)
summary(m7)
```
```{r}
m8=lm(medv~age,data=Boston)
summary(m8)
```
```{r}
m9=lm(medv~dis,data=Boston)
summary(m9)
```
```{r}
m10=lm(medv~rad,data=Boston)
summary(m10)
```
```{r}
m11=lm(medv~tax,data=Boston)
summary(m11)
```
```{r}
m12=lm(medv~ptratio,data=Boston)
summary(m12)
```
```{r}
m13=lm(medv~black,data=Boston)
summary(m13)
```
```{r}
m14=lm(medv~lstat,data=Boston)
summary(m14)
```
```{r}
model_mlm=lm(medv~.,data=Boston)
summary(model_mlm)
```

