---
title: "exercise 2"
output: html_document
date: "2026-07-04"
---

```{r}
library(tidyverse)
```



```{r}
library(ISLR)
```

```{r}
library(ISLR2)
```


```{r}
data(Auto)
```


```{r}
summary(Auto)
```


```{r}
str(Auto)

```
```{r}
sapply(Auto[,1:7],range)
```


```{r}
sapply(Auto[,1:7],mean)
```


```{r}
sapply(Auto[,1:7],sd)
```

```{r}
Auto.reduced = Auto[-c(10:84),]
sapply(Auto.reduced[,1:7],range)
sapply(Auto.reduced[,1:7],mean)
```


```{r}
sapply(Auto.reduced[,1:7],sd)
```


```{r}
pairs(Auto[,1:7])
```


```{r}
cor(Auto[,1:7])
```


```{r}
ggplot(data = Auto,mapping = aes(mpg,displacement))+geom_point()
```


```{r}
data(College)

```

```{r}
view(College)
```


```{r}
dim(College)
```


```{r}
summary(College)
```


```{r}
str(College)
```
```{r}
pairs(College[,1:5])
```
```{r}
attach(College)
```


```{r}
Elite = rep("no",nrow(College))
Elite[College$Top10perc>50]="yes"
College.df=data.frame(College,Elite)
```


```{r}
view(College.df)
```


```{r}
summary(College.df)
```
```{r}
str(College.df)
```

```{r}
boxplot(Outstate~Elite,data = College.df)
```


```{r}
hist(College$Apps,xlim=c(0,25000),xlab=("Applications"),main="Apps using default bin sizes")
```

```{r}
hist(College$Apps,xlim=c(0,25000),breaks = 25,xlab=("Applications"),main="Apps using smaller bin sizes")
```


```{r}
hist(College$Apps,xlim=c(0,25000),breaks = 25,xlab="Pct. new students from top 10% of H.S.class",main = "Top10Perc")
```


```{r}
hist(College$Outstate,xlab="Out-of-sate tuition",ylab = "Amount",main = "Outsate")
```


```{r}
```


```{r}
```

