---
title: "PRG_5_1U24DS040"
output: html_document
date: "2026-08-28"
---

```{r}
install.packages("MASS")
```

```{r}
library(tidyverse)
library(ISLR)
```
```{r}
library(MASS)
```

```{r}
data(Auto)
auto=data.frame(Auto)
```
```{r}
attach(auto)
```
```{r}
view (auto)
```

```{r}
dim(auto)
```

```{r}
mpg01<-rep(0,nrow(auto))
mpg01[auto[,'mpg']>median(auto[,'mpg'])]<-1
mpg01=as.factor(mpg01)
auto01=data.frame(auto,mpg01)
table(mpg01)
```
```{r}
 view(mpg01)
```

```{r}
par(mfrow=c(2,2))
boxplot(acceleration~mpg01,auto01,main="Accel~mpg01")
boxplot(weight~mpg01,auto01,main="Weight~mpg01")
boxplot(horsepower~mpg01,auto01,main="horsepower~mpg01")
boxplot(displacement~mpg01,auto01,main="disp~mpg01")

```
```{r}
trainig_data=auto01[1:196,]
testing_data=auto01[196:392,]
```

```{r}
glm_data=glm(mpg01~horsepower+displacement,family=binomial,trainig_data)
summary(glm_data)
```
```{r}
logit_pred=predict(glm_data,testing_data[,c('horsepower','weight','displacement')])
logit_class=ifelse(logit_pred>0.5,1,0)
table(logit_class,testing_data[,'mpg01'])
```
```{r}
(65+95)/(65+95+35+2)
```

