---
title: "program5"
output: html_document
date: "2026-08-28"
---



```{r}
library(tidyverse)
library(MASS)
library(ISLR)
```


```{r}
data(Auto)
auto=data.frame(Auto)
```

```{r}
?Auto
```

```{r}
attach(auto)
```

```{r}
mpg01<-rep(0,nrow(auto))
mpg01[auto[,'mpg']>median(auto[,'mpg'])]<-1
mpg01=as.factor(mpg01)
auto1=data.frame(auto,mpg01)
table(mpg01)

```

```{r}
par(mfrow=c(2,2))
boxplot(acceleration~mpg01,auto1,main="accel~mpg01")
boxplot(weight~mpg01,auto1,main="weight~mpg01")
boxplot(horsepower~mpg01,auto1,main="horsep~mpg01")
boxplot(displacement~mpg01,auto1,main="disp~mpg01")

```

```{r}

traning_data=auto1[1:196,]
testing_data=auto1[196:392,]
```

```{r}
glm_data=glm(mpg01~horsepower+displacement,family= binomial,traning_data)
summary(glm_data)

```

```{r}
logit_pred=predict(glm_data,testing_data[,c('horsepower','weight','displacement')])
logit_class=ifelse(logit_pred>0.5,1,0)
table(logit_class,testing_data[,'mpg01'])

```


```{r}
(65+95)/(65+35+2+95)

```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

