---
title: "program2_1U24DS030"
output: html_document
date: "2026-07-10"
---

```{r}
library(tidyverse)
library(ISLR)
library(ISLR2)
```


```{r}
data(Auto)
attach(Auto)
```


```{r}
view(Auto)
dim(Auto)
```


```{r}
head(Auto)
tail(Auto)
```


```{r}
summary(Auto)
```


```{r}
str(Auto)
```


```{r}
?Auto
```


```{r}
for(i in c(1,3,4,5,6,7))
{
  print(range(Auto[,i]))
}
```


```{r}
for(i in c(1,3,4,5,6,7))
{
  print(mean(Auto[,i]))
}

```
```{r}
for(i in c(1,3,4,5,6,7))
{
  print(median(Auto[,i]))
}
```


```{r}
for(i in c(1,3,4,5,6,7))
{
  print(sd(Auto[,i]))
}
```
```{r}
remove=Auto[-c(10:85),]
for(i in c(1,3,4,5,6,7))
{
  print(range(remove[,i]))
}
```


```{r}
str(remove)
```


```{r}
view(remove)
dim(remove)
```


```{r}
for(i in c(1,3,4,5,6,7))
{
  print(mean(remove[,i]))
}

```
```{r}
for(i in c(1,3,4,5,6,7))
{
  print(sd(remove[,i]))
}
```


```{r}
for(i in c(1,3,4,5,6,7))
{
  print(summary(remove[,i]))
}
```


```{r}
ggplot(remove,mapping=aes(cylinders,mpg))+geom_point(color="pink")
```


```{r}
plot(Auto$horsepower,Auto$mpg)
```


```{r}
pairs(Auto)
```


```{r}
plot(Auto$name,Auto$mpg)
```


```{r}
plot(Auto$origin,Auto$mpg)
```

