---
title: "program6"
output: html_document
date: "2026-08-28"
---

```{r}
library(tidyverse)
library(ISLR)
library(MASS)
```
```{r}
data(Auto)
Auto=data.frame(Auto)
```
```{r}
?Auto
```
```{r}
view(Auto)
```
```{r}
dim(Auto)
attach(Auto)
```
```{r}
str(Auto)
head(Auto)
tail(Auto)
```

```{r}
mpg01<-rep(0,nrow(Auto))
mpg01[Auto[,'mpg']>median(Auto[,'mpg'])]<-1
mpg01=as.factor(mpg01)
Auto01=data.frame(Auto,mpg01)
table(mpg01)
```
```{r}
par(mfrow=c(2,2))
boxplot(acceleration~mpg01,data,main="Accel~mpg01")
boxplot(weight~mpg01,data,main="weight~mpg01")
boxplot(horsepower~mpg01,data,main="horsep~mpg01")
boxplot(displacement~mpg01,data,main="disp~mpg01")
```
```{r}
data=train_data=Auto01[1:196,]
data=test_data=Auto01[196:392,]
```
```{r}
glm_fit=glm(mpg01~horsepower+displacement,family=binomial,data=train_data)
summary(glm_fit)
```
```{r}
logit.pred=predict(glm_fit,test_data[,c('horsepower','weight','displacement')])
logit.class=ifelse(logit.pred>0.5,1,0)
table(logit.class,test_data[,'mpg01'])
```
```{r}
mean(logit.class!=test_data[,"mpg01"])
```
```{r}
logit.class=ifelse(logit.pred>0.25,1,0)
table(logit.class,test_data[,'mpg01'])
```
```{r}
mean(logit.class!=test_data[,'mpg01'])
```


