---
title: "1U24DS013_program5"
author: "GOKUL"
date: "2026-08-28"
output: html_document
---

```{r}
library(tidyverse)
library(ISLR)
library(MASS)
```
```{r}
data("auto")
Auto=data.frame(Auto)
```
```{r}
?Auto
```
```{r}
view(Auto)
```
```{r}
head(Auto)
```
```{r}
tail(Auto)
```
```{r}
dim(Auto)
```
```{r}
attach(Auto)
```
```{r}
str(Auto)
```
```{r}
summary(Auto)
```
```{r}
mpg01<-rep(0,nrow(Auto))
mpg01[Auto[,'mpg']>median(Auto[,'mpg'])]<-1
mpg01=as.factor(mpg01)
data=data.frame(Auto,mpg01)
table(mpg01)
```
```{r}
par(mfrow=c(2,2))
boxplot(acceleration~mpg01,data,main="accel~mpg01")
boxplot(weight~mpg01,data,main="weight~mpg01")
boxplot(horsepower~mpg01,data,main="horsep~mpg01")
boxplot(displacement~mpg01,data,main="disp~mpg01")
```
```{r}
training_data=data[1:196,]
testing_data=data[196:392,]
```
```{r}
logit.fit=glm(mpg01~horsepower+displacement,family=binomial,training_data)
summary(logit.fit)
```
```{r}
logit.pred=predict(logit.fit,testing_data[,c('horsepower','weight','displacement')])
logit.class=ifelse(logit.pred>0.5,1,0)
table(logit.class,testing_data[,'mpg01'])
```

