---
title: "8th program"
output: html_document
date: "2026-09-23"
---
```{r}
library(ISLR)
names(Smarket)
```


```{r}
dim(Smarket)
```


```{r}
summary(Smarket)
```


```{r}
pairs(Smarket)
cor(Smarket[,-9])
```


```{r}
attach(Smarket)
plot(Volume)
```


```{r}
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume,data=Smarket,family=binomial)
summary(glm.fit)
```


```{r}
coef(glm.fit)
summary(glm.fit)$coef
```


```{r}
summary(glm.fit)$coef[,4]
```


```{r}
glm.probs=predict(glm.fit,type="response")
glm.probs[1:10]
contrasts(Direction)
```


```{r}
glm.pred=rep("Down",1250)
glm.pred[glm.probs>.5]="up"
```


```{r}
table(glm.pred,Direction)
(507+145)/1250
mean(glm.pred==Direction)
```


```{r}
train=(Year<2005)
Smarket.2005=Smarket[!train,]
dim(Smarket.2005)
Direction.2005=Direction[!train]
```


```{r}
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume,data=Smarket,family=binomial,subset=train)
glm.probs=predict(glm.fit,Smarket.2005,type="response")
```


```{r}
glm.pred=rep("Down",252)
glm.pred[glm.probs>.5]="up"
table(glm.pred,Direction.2005)
mean(glm.pred==Direction.2005)
mean(glm.pred!=Direction.2005)
```


```{r}
glm.fit=glm(Direction~Lag1+Lag2,data=Smarket,family=binomial,subset=train)
glm.probs=predict(glm.fit,Smarket.2005,type="response")
glm.pred=rep("Doen",252)
glm.pred[glm.probs>.5]="up"
table(glm.pred,Direction.2005)
mean(glm.pred==Direction.2005)
106/(106+76)
```

