---
title: "program2_1U24DS026"
author: "program"
date: "2026-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ISLR)
library(ISLR2)
```

```{r}
data(Auto)
```

```{r}
attach(Auto)
```

```{r}
summary(Auto)
```
```{r}
dim(Auto)
```

```{r}
?Auto
```


```{r}
view(Auto)
```

```{r}
head(Auto)
```

```{r}
tail(Auto)
```

```{r}
str(Auto)
```
```{r}
for (i in c(1,3,4,5,6,7))
{
  print(range(Auto[,i]))
}
```
```{r}
for (i in c(1,3,4,5,6,7))
{
  print(mean(Auto[,i]))
}
```
```{r}
for (i in c(1,3,4,5,6,7))
{
  print(min(Auto[,i]))
}
```
```{r}
for (i in c(1,3,4,5,6,7))
{
  print(max(Auto[,i]))
}
```
```{r}
for (i in c(1,3,4,5,6,7))
{
  print(sd(Auto[,i]))
}
```
```{r}
for (i in c(1,3,4,5,6,7))
{
  print(median(Auto[,i]))
}
```
```{r}
remove=Auto[-c(10:85),]
```

```{r}
view(remove)
```

```{r}
?remove
```

```{r}
dim(remove)
```
```{r}
summary(remove)
```
```{r}
str(remove)
```
```{r}
plot(Auto$horsepower,Auto$mpg)
```
```{r}
pairs(Auto)
```
```{r}
plot(Auto$origin,Auto$mpg)
```



















